const API_CONFIGS = {
  API_URL: "<API URL HERE>",
  CLIENT_ID: "<CLIENT ID HERE>",
  CLIENT_SECRET:
    "<CLIENT SECRET HERE>",
  GRANT_PASSWORD: "<GRANT METHOD HERE>",
};

export default API_CONFIGS;
