export default Object.freeze({
  LOGIN: "LOGIN",
  REGISTER: "REGISTER",
  DASHBOARD: "DASHBOARD",
  PROFILE: "PROFILE",
  REPORT_LIST: "REPORT_LIST",
  REPORT_DETAIL: "REPORT_DETAIL",
  CHECK_VULNERABILITY: "CHECK_VULNERABILITY",
  PAST_DISEASE: "PAST_DISEASE",
});
